### ISSUE TITLE
Trouble with transaction

### ISSUE THREAD

**Issue by bconte** [simon-kuster/BlazorDexie#13]
Using BlazorDixie 1.5.1 in a .net8 Blazor Web app:

Using the following code:
`          await _dixieContext.Transaction("rw",
             ["Accounts"],
             60000,
             async () =>
         {
            <stuff>
         });
     }`

I'm getting the following exception:

--
Microsoft.JSInterop.JSException: 'Invalid table argument to Dexie.transaction(). Only Table or String are allowed
TypeError: Invalid table argument to Dexie.transaction(). Only Table or String are allowed
    at https://unpkg.com/dexie/dist/dexie.js:4851:31
    at Array.map (<anonymous>)
    at Dexie._transaction (https://unpkg.com/dexie/dist/dexie.js:4848:37)
    at Dexie.transaction (https://unpkg.com/dexie/dist/dexie.js:4837:38)
    at executeTransaction (https://localhost:8071/_content/BlazorDexie/scripts/staticCommandExecuter.js:27:14)
    at Module.executeNonQuery (https://localhost:8071/_content/BlazorDexie/scripts/staticCommandExecuter.js:5:19)
    at https://localhost:8071/_framework/blazor.web.js:1:3244
    at new Promise (<anonymous>)
    at y.beginInvokeJSFromDotNet (https://localhost:8071/_framework/blazor.web.js:1:3201)
    at fn._invokeClientMethod (https://localhost:8071/_framework/blazor.web.js:1:62914)'

--
As you can see i am supplying a string, so i'm not sure what could be the problem.  

Thanks!

**Comment by simon-kuster** [comment]
The problem seems to be that the store/table "accounts" does not exists. It could be a problem with PascalCase and CamelCase. Depending on whether the camelCaseStoreNames parameter is set to true or false when a db instance is created, the store names are created either in pascalcase or camelcase. 

There was an error in the method Db.Transaction that caused a problem if camelCaseStoreNames was set to false (default). This error has been fixed with version 1.5.2. So update to version  1.5.2 and try again.

**Comment by bconte** [comment]
That was it, works now, thank you!
